name: Build and Deploy Weather Website to GHCR

on:
  repository_dispatch:
    types: [weather-update]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update HTML with weather data
        uses: qetza/replacetokens-action@v1
        with:
          sources: 'index.html'
          variables: |
            {
              "temperature": "${{ github.event.client_payload.temperature }}",
              "humidity": "${{ github.event.client_payload.humidity }}",
              "pressure": "${{ github.event.client_payload.pressure }}",
              "timestamp": "${{ github.event.client_payload.timestamp }}"
            }

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image to GHCR
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/weatherpage:latest

      - name: Trigger Portainer webhook
        uses: distributhor/workflow-webhook@v3
        with:
          webhook_url: ${{ secrets.PORTAINER_WEBHOOK_URL }}
